{% set name = "pyplif-hippos" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/radifar/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3bf409011254e874b54bf6e896a291f73c2f3b9c915acbf1658b4f0da0802faa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.6
    - openbabel >=2.2
    - bitarray >=0.8

test:
  imports:
    - pyplif_hippos

about:
  home: https://github.com/radifar/PyPLIF-HIPPOS
  license: MHPND
  license_file: LICENSE.txt
  summary: HIPPOS Is PyPLIF On Steroids
  description: |
    A Molecular Interaction Fingerprinting Tool for Docking Results of Autodock Vina and PLANTS.
  doc_url: https://pyplif-hippos.readthedocs.io/
  dev_url: https://github.com/radifar/PyPLIF-HIPPOS

extra:
  recipe-maintainers:
    - radifar
