{% set name = "pyplif-hippos" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/radifar/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 42f1fe2f33be1eaae2d1261b2d4eedba9f57c2ae6b8c55cd345370812caf03f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.6
    - openbabel >=2.2
    - bitarray >=0.8

test:
  imports:
    - pyplif_hippos

about:
  home: https://github.com/radifar/PyPLIF-HIPPOS
  license: MHPND
  license_file: LICENSE.txt
  summary: HIPPOS Is PyPLIF On Steroids
  description: |
    A Molecular Interaction Fingerprinting Tool for Docking Results of Autodock Vina and PLANTS.
  doc_url: https://pyplif-hippos.readthedocs.io/
  dev_url: https://github.com/radifar/PyPLIF-HIPPOS

extra:
  recipe-maintainers:
    - radifar
